// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from "@prisma/orm-postgres/target/codec-types";
import type { QueryOperationTypes as PgTargetQueryOps } from "@prisma/orm-postgres/target/operation-types";

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from "@prisma/orm-postgres/family-contract/types";
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from "@prisma/orm-postgres/contract/types";

export type StorageHash =
  StorageHashBase<"b57ea8c4127001ded51341604ccac878b23f5516a30341ad3c9a1f5c88c9328c">;
export type ExecutionHash =
  ExecutionHashBase<"00b3e1ca59b88aab8c0b81812b52c2b4cc9e24ca2111711474c012c1fec743f4">;
export type ProfileHash =
  ProfileHashBase<"3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2">;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly "pg/float@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/float4@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/float8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int8number@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "pg/float8@1"; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly "pg/int@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/int8number@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: {
      readonly output: "pg/int8number@1";
      readonly nullable: false;
    };
    readonly anyInput: { readonly output: "pg/int8number@1"; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: "pg/int8@1"; readonly nullable: false };
    readonly anyInput: { readonly output: "pg/int8@1"; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly "pg/char@1": { readonly output: "pg/char@1"; readonly nullable: true };
      readonly "pg/date-string@1": {
        readonly output: "pg/date-string@1";
        readonly nullable: true;
      };
      readonly "pg/date-temporal@1": {
        readonly output: "pg/date-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/enum@1": { readonly output: "pg/enum@1"; readonly nullable: true };
      readonly "pg/float@1": { readonly output: "pg/float@1"; readonly nullable: true };
      readonly "pg/float4@1": { readonly output: "pg/float4@1"; readonly nullable: true };
      readonly "pg/float8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/inet@1": { readonly output: "pg/inet@1"; readonly nullable: true };
      readonly "pg/int@1": { readonly output: "pg/int@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/int2@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/int4@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/int8@1"; readonly nullable: true };
      readonly "pg/int8number@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/text-array@1": {
        readonly output: "pg/text-array@1";
        readonly nullable: true;
      };
      readonly "pg/text@1": { readonly output: "pg/text@1"; readonly nullable: true };
      readonly "pg/time-string@1": {
        readonly output: "pg/time-string@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/time-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-string@1": {
        readonly output: "pg/timestamp-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-temporal@1": {
        readonly output: "pg/timestamp-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-date@1": {
        readonly output: "pg/timestamptz-date@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-string@1": {
        readonly output: "pg/timestamptz-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-temporal@1": {
        readonly output: "pg/timestamptz-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timetz@1": { readonly output: "pg/timetz@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/varchar@1": { readonly output: "pg/text@1"; readonly nullable: true };
      readonly "sql/char@1": { readonly output: "sql/char@1"; readonly nullable: true };
      readonly "sql/float@1": { readonly output: "sql/float@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "sql/int@1"; readonly nullable: true };
      readonly "sql/text@1": { readonly output: "sql/text@1"; readonly nullable: true };
      readonly "sql/varchar@1": { readonly output: "pg/text@1"; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly "pg/char@1": { readonly output: "pg/char@1"; readonly nullable: true };
      readonly "pg/date-string@1": {
        readonly output: "pg/date-string@1";
        readonly nullable: true;
      };
      readonly "pg/date-temporal@1": {
        readonly output: "pg/date-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/enum@1": { readonly output: "pg/enum@1"; readonly nullable: true };
      readonly "pg/float@1": { readonly output: "pg/float@1"; readonly nullable: true };
      readonly "pg/float4@1": { readonly output: "pg/float4@1"; readonly nullable: true };
      readonly "pg/float8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/inet@1": { readonly output: "pg/inet@1"; readonly nullable: true };
      readonly "pg/int@1": { readonly output: "pg/int@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/int2@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/int4@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/int8@1"; readonly nullable: true };
      readonly "pg/int8number@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/text-array@1": {
        readonly output: "pg/text-array@1";
        readonly nullable: true;
      };
      readonly "pg/text@1": { readonly output: "pg/text@1"; readonly nullable: true };
      readonly "pg/time-string@1": {
        readonly output: "pg/time-string@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/time-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-string@1": {
        readonly output: "pg/timestamp-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-temporal@1": {
        readonly output: "pg/timestamp-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-date@1": {
        readonly output: "pg/timestamptz-date@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-string@1": {
        readonly output: "pg/timestamptz-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-temporal@1": {
        readonly output: "pg/timestamptz-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timetz@1": { readonly output: "pg/timetz@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/varchar@1": { readonly output: "pg/text@1"; readonly nullable: true };
      readonly "sql/char@1": { readonly output: "sql/char@1"; readonly nullable: true };
      readonly "sql/float@1": { readonly output: "sql/float@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "sql/int@1"; readonly nullable: true };
      readonly "sql/text@1": { readonly output: "sql/text@1"; readonly nullable: true };
      readonly "sql/varchar@1": { readonly output: "pg/text@1"; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly "pg/float@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/float4@1": { readonly output: "pg/float4@1"; readonly nullable: true };
      readonly "pg/float8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "sql/int@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly "pg/int@1": { readonly output: "pg/int8@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/int8@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/int8@1"; readonly nullable: true };
      readonly "pg/int8@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": { readonly output: "pg/int8@1"; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<
  CodecId extends string,
  Encoded,
> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]["json"]
    ? Encoded
    : CodecTypes[CodecId]["json"]
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Application: {
      readonly appliedAt: CodecTypes["pg/date-string@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly status: "PENDING" | "ACCEPTED" | "REJECTED";
      readonly taskId: CodecTypes["pg/text@1"]["output"];
      readonly workerId: CodecTypes["pg/text@1"]["output"];
    };
    readonly Notification: {
      readonly createdAt: CodecTypes["pg/date-string@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly isRead: CodecTypes["pg/bool@1"]["output"];
      readonly message: CodecTypes["pg/text@1"]["output"];
      readonly title: CodecTypes["pg/text@1"]["output"];
      readonly type:
        | "NEW_APPLICATION"
        | "APPLICATION_ACCEPTED"
        | "APPLICATION_REJECTED"
        | "TASK_COMPLETED";
      readonly userId: CodecTypes["pg/text@1"]["output"];
    };
    readonly Task: {
      readonly budget: CodecTypes["pg/int4@1"]["output"];
      readonly category: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/date-string@1"]["output"];
      readonly description: CodecTypes["pg/text@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly latitude: CodecTypes["pg/float8@1"]["output"] | null;
      readonly location: CodecTypes["pg/text@1"]["output"];
      readonly longitude: CodecTypes["pg/float8@1"]["output"] | null;
      readonly posterId: CodecTypes["pg/text@1"]["output"];
      readonly scheduleDate: CodecTypes["pg/text@1"]["output"];
      readonly scheduleTime: CodecTypes["pg/text@1"]["output"];
      readonly status: "OPEN" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
      readonly title: CodecTypes["pg/text@1"]["output"];
      readonly updatedAt: CodecTypes["pg/date-string@1"]["output"];
    };
    readonly Transaction: {
      readonly amount: CodecTypes["pg/int4@1"]["output"];
      readonly commissionAmount: CodecTypes["pg/int4@1"]["output"];
      readonly commissionRate: CodecTypes["pg/float8@1"]["output"];
      readonly createdAt: CodecTypes["pg/date-string@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly netAmount: CodecTypes["pg/int4@1"]["output"];
      readonly status: "PENDING" | "PAID";
      readonly taskId: CodecTypes["pg/text@1"]["output"];
    };
    readonly User: {
      readonly createdAt: CodecTypes["pg/date-string@1"]["output"];
      readonly email: CodecTypes["pg/text@1"]["output"];
      readonly hashedPassword: CodecTypes["pg/text@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly image: CodecTypes["pg/text@1"]["output"] | null;
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly role: "POSTER" | "WORKER";
      readonly updatedAt: CodecTypes["pg/date-string@1"]["output"];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Application: {
      readonly appliedAt: CodecTypes["pg/date-string@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly status: "PENDING" | "ACCEPTED" | "REJECTED";
      readonly taskId: CodecTypes["pg/text@1"]["input"];
      readonly workerId: CodecTypes["pg/text@1"]["input"];
    };
    readonly Notification: {
      readonly createdAt: CodecTypes["pg/date-string@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly isRead: CodecTypes["pg/bool@1"]["input"];
      readonly message: CodecTypes["pg/text@1"]["input"];
      readonly title: CodecTypes["pg/text@1"]["input"];
      readonly type:
        | "NEW_APPLICATION"
        | "APPLICATION_ACCEPTED"
        | "APPLICATION_REJECTED"
        | "TASK_COMPLETED";
      readonly userId: CodecTypes["pg/text@1"]["input"];
    };
    readonly Task: {
      readonly budget: CodecTypes["pg/int4@1"]["input"];
      readonly category: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/date-string@1"]["input"];
      readonly description: CodecTypes["pg/text@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly latitude: CodecTypes["pg/float8@1"]["input"] | null;
      readonly location: CodecTypes["pg/text@1"]["input"];
      readonly longitude: CodecTypes["pg/float8@1"]["input"] | null;
      readonly posterId: CodecTypes["pg/text@1"]["input"];
      readonly scheduleDate: CodecTypes["pg/text@1"]["input"];
      readonly scheduleTime: CodecTypes["pg/text@1"]["input"];
      readonly status: "OPEN" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
      readonly title: CodecTypes["pg/text@1"]["input"];
      readonly updatedAt: CodecTypes["pg/date-string@1"]["input"];
    };
    readonly Transaction: {
      readonly amount: CodecTypes["pg/int4@1"]["input"];
      readonly commissionAmount: CodecTypes["pg/int4@1"]["input"];
      readonly commissionRate: CodecTypes["pg/float8@1"]["input"];
      readonly createdAt: CodecTypes["pg/date-string@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly netAmount: CodecTypes["pg/int4@1"]["input"];
      readonly status: "PENDING" | "PAID";
      readonly taskId: CodecTypes["pg/text@1"]["input"];
    };
    readonly User: {
      readonly createdAt: CodecTypes["pg/date-string@1"]["input"];
      readonly email: CodecTypes["pg/text@1"]["input"];
      readonly hashedPassword: CodecTypes["pg/text@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly image: CodecTypes["pg/text@1"]["input"] | null;
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly role: "POSTER" | "WORKER";
      readonly updatedAt: CodecTypes["pg/date-string@1"]["input"];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly applications: {
      readonly appliedAt: CodecTypes["pg/date-string@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly status: "PENDING" | "ACCEPTED" | "REJECTED";
      readonly taskId: CodecTypes["pg/text@1"]["output"];
      readonly workerId: CodecTypes["pg/text@1"]["output"];
    };
    readonly notifications: {
      readonly createdAt: CodecTypes["pg/date-string@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly isRead: CodecTypes["pg/bool@1"]["output"];
      readonly message: CodecTypes["pg/text@1"]["output"];
      readonly title: CodecTypes["pg/text@1"]["output"];
      readonly type:
        | "NEW_APPLICATION"
        | "APPLICATION_ACCEPTED"
        | "APPLICATION_REJECTED"
        | "TASK_COMPLETED";
      readonly userId: CodecTypes["pg/text@1"]["output"];
    };
    readonly tasks: {
      readonly budget: CodecTypes["pg/int4@1"]["output"];
      readonly category: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/date-string@1"]["output"];
      readonly description: CodecTypes["pg/text@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly latitude: CodecTypes["pg/float8@1"]["output"] | null;
      readonly location: CodecTypes["pg/text@1"]["output"];
      readonly longitude: CodecTypes["pg/float8@1"]["output"] | null;
      readonly posterId: CodecTypes["pg/text@1"]["output"];
      readonly scheduleDate: CodecTypes["pg/text@1"]["output"];
      readonly scheduleTime: CodecTypes["pg/text@1"]["output"];
      readonly status: "OPEN" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
      readonly title: CodecTypes["pg/text@1"]["output"];
      readonly updatedAt: CodecTypes["pg/date-string@1"]["output"];
    };
    readonly transactions: {
      readonly amount: CodecTypes["pg/int4@1"]["output"];
      readonly commissionAmount: CodecTypes["pg/int4@1"]["output"];
      readonly commissionRate: CodecTypes["pg/float8@1"]["output"];
      readonly createdAt: CodecTypes["pg/date-string@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly netAmount: CodecTypes["pg/int4@1"]["output"];
      readonly status: "PENDING" | "PAID";
      readonly taskId: CodecTypes["pg/text@1"]["output"];
    };
    readonly users: {
      readonly createdAt: CodecTypes["pg/date-string@1"]["output"];
      readonly email: CodecTypes["pg/text@1"]["output"];
      readonly hashedPassword: CodecTypes["pg/text@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly image: CodecTypes["pg/text@1"]["output"] | null;
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly role: "POSTER" | "WORKER";
      readonly updatedAt: CodecTypes["pg/date-string@1"]["output"];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly applications: {
      readonly appliedAt: CodecTypes["pg/date-string@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly status: "PENDING" | "ACCEPTED" | "REJECTED";
      readonly taskId: CodecTypes["pg/text@1"]["input"];
      readonly workerId: CodecTypes["pg/text@1"]["input"];
    };
    readonly notifications: {
      readonly createdAt: CodecTypes["pg/date-string@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly isRead: CodecTypes["pg/bool@1"]["input"];
      readonly message: CodecTypes["pg/text@1"]["input"];
      readonly title: CodecTypes["pg/text@1"]["input"];
      readonly type:
        | "NEW_APPLICATION"
        | "APPLICATION_ACCEPTED"
        | "APPLICATION_REJECTED"
        | "TASK_COMPLETED";
      readonly userId: CodecTypes["pg/text@1"]["input"];
    };
    readonly tasks: {
      readonly budget: CodecTypes["pg/int4@1"]["input"];
      readonly category: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/date-string@1"]["input"];
      readonly description: CodecTypes["pg/text@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly latitude: CodecTypes["pg/float8@1"]["input"] | null;
      readonly location: CodecTypes["pg/text@1"]["input"];
      readonly longitude: CodecTypes["pg/float8@1"]["input"] | null;
      readonly posterId: CodecTypes["pg/text@1"]["input"];
      readonly scheduleDate: CodecTypes["pg/text@1"]["input"];
      readonly scheduleTime: CodecTypes["pg/text@1"]["input"];
      readonly status: "OPEN" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
      readonly title: CodecTypes["pg/text@1"]["input"];
      readonly updatedAt: CodecTypes["pg/date-string@1"]["input"];
    };
    readonly transactions: {
      readonly amount: CodecTypes["pg/int4@1"]["input"];
      readonly commissionAmount: CodecTypes["pg/int4@1"]["input"];
      readonly commissionRate: CodecTypes["pg/float8@1"]["input"];
      readonly createdAt: CodecTypes["pg/date-string@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly netAmount: CodecTypes["pg/int4@1"]["input"];
      readonly status: "PENDING" | "PAID";
      readonly taskId: CodecTypes["pg/text@1"]["input"];
    };
    readonly users: {
      readonly createdAt: CodecTypes["pg/date-string@1"]["input"];
      readonly email: CodecTypes["pg/text@1"]["input"];
      readonly hashedPassword: CodecTypes["pg/text@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly image: CodecTypes["pg/text@1"]["input"] | null;
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly role: "POSTER" | "WORKER";
      readonly updatedAt: CodecTypes["pg/date-string@1"]["input"];
    };
  };
};

export namespace Models {
  export type public_Application = {
    appliedAt: CodecTypes["pg/date-string@1"]["output"];
    id: CodecTypes["pg/text@1"]["output"];
    status: "PENDING" | "ACCEPTED" | "REJECTED";
    taskId: CodecTypes["pg/text@1"]["output"];
    workerId: CodecTypes["pg/text@1"]["output"];
    task: public_Task;
    worker: public_User;
    readonly [RelationKeys]?: "task" | "worker";
  };
  export type public_Notification = {
    createdAt: CodecTypes["pg/date-string@1"]["output"];
    id: CodecTypes["pg/text@1"]["output"];
    isRead: CodecTypes["pg/bool@1"]["output"];
    message: CodecTypes["pg/text@1"]["output"];
    title: CodecTypes["pg/text@1"]["output"];
    type:
      | "NEW_APPLICATION"
      | "APPLICATION_ACCEPTED"
      | "APPLICATION_REJECTED"
      | "TASK_COMPLETED";
    userId: CodecTypes["pg/text@1"]["output"];
    user: public_User;
    readonly [RelationKeys]?: "user";
  };
  export type public_Task = {
    budget: CodecTypes["pg/int4@1"]["output"];
    category: CodecTypes["pg/text@1"]["output"];
    createdAt: CodecTypes["pg/date-string@1"]["output"];
    description: CodecTypes["pg/text@1"]["output"];
    id: CodecTypes["pg/text@1"]["output"];
    latitude: CodecTypes["pg/float8@1"]["output"] | null;
    location: CodecTypes["pg/text@1"]["output"];
    longitude: CodecTypes["pg/float8@1"]["output"] | null;
    posterId: CodecTypes["pg/text@1"]["output"];
    scheduleDate: CodecTypes["pg/text@1"]["output"];
    scheduleTime: CodecTypes["pg/text@1"]["output"];
    status: "OPEN" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
    title: CodecTypes["pg/text@1"]["output"];
    updatedAt: CodecTypes["pg/date-string@1"]["output"];
    poster: public_User;
    readonly [RelationKeys]?: "poster";
  };
  export type public_Transaction = {
    amount: CodecTypes["pg/int4@1"]["output"];
    commissionAmount: CodecTypes["pg/int4@1"]["output"];
    commissionRate: CodecTypes["pg/float8@1"]["output"];
    createdAt: CodecTypes["pg/date-string@1"]["output"];
    id: CodecTypes["pg/text@1"]["output"];
    netAmount: CodecTypes["pg/int4@1"]["output"];
    status: "PENDING" | "PAID";
    taskId: CodecTypes["pg/text@1"]["output"];
    task: public_Task;
    readonly [RelationKeys]?: "task";
  };
  export type public_User = {
    createdAt: CodecTypes["pg/date-string@1"]["output"];
    email: CodecTypes["pg/text@1"]["output"];
    hashedPassword: CodecTypes["pg/text@1"]["output"];
    id: CodecTypes["pg/text@1"]["output"];
    image: CodecTypes["pg/text@1"]["output"] | null;
    name: CodecTypes["pg/text@1"]["output"];
    role: "POSTER" | "WORKER";
    updatedAt: CodecTypes["pg/date-string@1"]["output"];
    readonly [RelationKeys]?: never;
  };
}

export declare const models: {
  public: {
    Application: Models.public_Application;
    Notification: Models.public_Notification;
    Task: Models.public_Task;
    Transaction: Models.public_Transaction;
    User: Models.public_User;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: "public";
        readonly kind: "postgres-schema";
        readonly entries: {
          readonly table: {
            readonly applications: {
              columns: {
                readonly appliedAt: {
                  readonly nativeType: "date";
                  readonly codecId: "pg/date-string@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "literal";
                    readonly value: DefaultLiteralValue<"pg/text@1", "PENDING">;
                  };
                };
                readonly taskId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly workerId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["taskId", "workerId"] }];
              indexes: readonly [
                {
                  readonly name: "applications_status_idx_e98638ab";
                  readonly prefix: "applications_status_idx";
                  readonly columns: readonly ["status"];
                  readonly unique: false;
                },
                {
                  readonly name: "applications_taskId_idx_4965c936";
                  readonly prefix: "applications_taskId_idx";
                  readonly columns: readonly ["taskId"];
                  readonly unique: false;
                },
                {
                  readonly name: "applications_workerId_idx_0b8f3a7c";
                  readonly prefix: "applications_workerId_idx";
                  readonly columns: readonly ["workerId"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "applications";
                    readonly columns: readonly ["taskId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "tasks";
                    readonly columns: readonly ["id"];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "applications";
                    readonly columns: readonly ["workerId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "users";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly notifications: {
              columns: {
                readonly createdAt: {
                  readonly nativeType: "date";
                  readonly codecId: "pg/date-string@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly isRead: {
                  readonly nativeType: "bool";
                  readonly codecId: "pg/bool@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "literal";
                    readonly value: DefaultLiteralValue<"pg/bool@1", false>;
                  };
                };
                readonly message: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly title: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly type: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: "notifications_isRead_idx_a2737ae3";
                  readonly prefix: "notifications_isRead_idx";
                  readonly columns: readonly ["isRead"];
                  readonly unique: false;
                },
                {
                  readonly name: "notifications_userId_idx_a489d58a";
                  readonly prefix: "notifications_userId_idx";
                  readonly columns: readonly ["userId"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "notifications";
                    readonly columns: readonly ["userId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "users";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly tasks: {
              columns: {
                readonly budget: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly category: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "date";
                  readonly codecId: "pg/date-string@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
                readonly description: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly latitude: {
                  readonly nativeType: "float8";
                  readonly codecId: "pg/float8@1";
                  readonly nullable: true;
                };
                readonly location: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly longitude: {
                  readonly nativeType: "float8";
                  readonly codecId: "pg/float8@1";
                  readonly nullable: true;
                };
                readonly posterId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly scheduleDate: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly scheduleTime: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "literal";
                    readonly value: DefaultLiteralValue<"pg/text@1", "OPEN">;
                  };
                };
                readonly title: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly updatedAt: {
                  readonly nativeType: "date";
                  readonly codecId: "pg/date-string@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: "tasks_category_idx_f2600f8e";
                  readonly prefix: "tasks_category_idx";
                  readonly columns: readonly ["category"];
                  readonly unique: false;
                },
                {
                  readonly name: "tasks_posterId_idx_981844b1";
                  readonly prefix: "tasks_posterId_idx";
                  readonly columns: readonly ["posterId"];
                  readonly unique: false;
                },
                {
                  readonly name: "tasks_status_idx_e98638ab";
                  readonly prefix: "tasks_status_idx";
                  readonly columns: readonly ["status"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "tasks";
                    readonly columns: readonly ["posterId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "users";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly transactions: {
              columns: {
                readonly amount: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly commissionAmount: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly commissionRate: {
                  readonly nativeType: "float8";
                  readonly codecId: "pg/float8@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "date";
                  readonly codecId: "pg/date-string@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly netAmount: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "literal";
                    readonly value: DefaultLiteralValue<"pg/text@1", "PENDING">;
                  };
                };
                readonly taskId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: "transactions_status_idx_e98638ab";
                  readonly prefix: "transactions_status_idx";
                  readonly columns: readonly ["status"];
                  readonly unique: false;
                },
                {
                  readonly name: "transactions_taskId_idx_4965c936";
                  readonly prefix: "transactions_taskId_idx";
                  readonly columns: readonly ["taskId"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "transactions";
                    readonly columns: readonly ["taskId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "tasks";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly users: {
              columns: {
                readonly createdAt: {
                  readonly nativeType: "date";
                  readonly codecId: "pg/date-string@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
                readonly email: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly hashedPassword: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly image: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly name: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly role: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly updatedAt: {
                  readonly nativeType: "date";
                  readonly codecId: "pg/date-string@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["email"] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly ApplicationStatus: {
              readonly kind: "valueSet";
              readonly values: readonly ["PENDING", "ACCEPTED", "REJECTED"];
            };
            readonly NotificationType: {
              readonly kind: "valueSet";
              readonly values: readonly [
                "NEW_APPLICATION",
                "APPLICATION_ACCEPTED",
                "APPLICATION_REJECTED",
                "TASK_COMPLETED",
              ];
            };
            readonly TaskStatus: {
              readonly kind: "valueSet";
              readonly values: readonly ["OPEN", "IN_PROGRESS", "COMPLETED", "CANCELLED"];
            };
            readonly TransactionStatus: {
              readonly kind: "valueSet";
              readonly values: readonly ["PENDING", "PAID"];
            };
            readonly UserRole: {
              readonly kind: "valueSet";
              readonly values: readonly ["POSTER", "WORKER"];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  "roots" | "domain"
> & {
  readonly target: "postgres";
  readonly targetFamily: "sql";
  readonly roots: {
    readonly applications: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "Application";
    };
    readonly notifications: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "Notification";
    };
    readonly tasks: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "Task";
    };
    readonly transactions: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "Transaction";
    };
    readonly users: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "User";
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Application: {
            readonly fields: {
              readonly appliedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/date-string@1";
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly taskId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly workerId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
            };
            readonly relations: {
              readonly task: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Task";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["taskId"];
                  readonly targetFields: readonly ["id"];
                };
              };
              readonly worker: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "User";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["workerId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "applications";
              readonly namespaceId: "public";
              readonly fields: {
                readonly appliedAt: { readonly column: "appliedAt" };
                readonly id: { readonly column: "id" };
                readonly status: { readonly column: "status" };
                readonly taskId: { readonly column: "taskId" };
                readonly workerId: { readonly column: "workerId" };
              };
            };
          };
          readonly Notification: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/date-string@1";
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly isRead: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/bool@1" };
              };
              readonly message: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "User";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["userId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "notifications";
              readonly namespaceId: "public";
              readonly fields: {
                readonly createdAt: { readonly column: "createdAt" };
                readonly id: { readonly column: "id" };
                readonly isRead: { readonly column: "isRead" };
                readonly message: { readonly column: "message" };
                readonly title: { readonly column: "title" };
                readonly type: { readonly column: "type" };
                readonly userId: { readonly column: "userId" };
              };
            };
          };
          readonly Task: {
            readonly fields: {
              readonly budget: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/int4@1" };
              };
              readonly category: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/date-string@1";
                };
              };
              readonly description: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly latitude: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/float8@1";
                };
              };
              readonly location: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly longitude: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/float8@1";
                };
              };
              readonly posterId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly scheduleDate: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly scheduleTime: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/date-string@1";
                };
              };
            };
            readonly relations: {
              readonly poster: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "User";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["posterId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "tasks";
              readonly namespaceId: "public";
              readonly fields: {
                readonly budget: { readonly column: "budget" };
                readonly category: { readonly column: "category" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly description: { readonly column: "description" };
                readonly id: { readonly column: "id" };
                readonly latitude: { readonly column: "latitude" };
                readonly location: { readonly column: "location" };
                readonly longitude: { readonly column: "longitude" };
                readonly posterId: { readonly column: "posterId" };
                readonly scheduleDate: { readonly column: "scheduleDate" };
                readonly scheduleTime: { readonly column: "scheduleTime" };
                readonly status: { readonly column: "status" };
                readonly title: { readonly column: "title" };
                readonly updatedAt: { readonly column: "updatedAt" };
              };
            };
          };
          readonly Transaction: {
            readonly fields: {
              readonly amount: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/int4@1" };
              };
              readonly commissionAmount: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/int4@1" };
              };
              readonly commissionRate: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/float8@1";
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/date-string@1";
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly netAmount: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/int4@1" };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly taskId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
            };
            readonly relations: {
              readonly task: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Task";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["taskId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "transactions";
              readonly namespaceId: "public";
              readonly fields: {
                readonly amount: { readonly column: "amount" };
                readonly commissionAmount: { readonly column: "commissionAmount" };
                readonly commissionRate: { readonly column: "commissionRate" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly id: { readonly column: "id" };
                readonly netAmount: { readonly column: "netAmount" };
                readonly status: { readonly column: "status" };
                readonly taskId: { readonly column: "taskId" };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/date-string@1";
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly hashedPassword: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly image: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/date-string@1";
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: "users";
              readonly namespaceId: "public";
              readonly fields: {
                readonly createdAt: { readonly column: "createdAt" };
                readonly email: { readonly column: "email" };
                readonly hashedPassword: { readonly column: "hashedPassword" };
                readonly id: { readonly column: "id" };
                readonly image: { readonly column: "image" };
                readonly name: { readonly column: "name" };
                readonly role: { readonly column: "role" };
                readonly updatedAt: { readonly column: "updatedAt" };
              };
            };
          };
        };
        readonly enum: {
          readonly ApplicationStatus: {
            readonly codecId: "pg/text@1";
            readonly members: readonly [
              { readonly name: "PENDING"; readonly value: "PENDING" },
              { readonly name: "ACCEPTED"; readonly value: "ACCEPTED" },
              { readonly name: "REJECTED"; readonly value: "REJECTED" },
            ];
          };
          readonly NotificationType: {
            readonly codecId: "pg/text@1";
            readonly members: readonly [
              { readonly name: "NEW_APPLICATION"; readonly value: "NEW_APPLICATION" },
              {
                readonly name: "APPLICATION_ACCEPTED";
                readonly value: "APPLICATION_ACCEPTED";
              },
              {
                readonly name: "APPLICATION_REJECTED";
                readonly value: "APPLICATION_REJECTED";
              },
              { readonly name: "TASK_COMPLETED"; readonly value: "TASK_COMPLETED" },
            ];
          };
          readonly TaskStatus: {
            readonly codecId: "pg/text@1";
            readonly members: readonly [
              { readonly name: "OPEN"; readonly value: "OPEN" },
              { readonly name: "IN_PROGRESS"; readonly value: "IN_PROGRESS" },
              { readonly name: "COMPLETED"; readonly value: "COMPLETED" },
              { readonly name: "CANCELLED"; readonly value: "CANCELLED" },
            ];
          };
          readonly TransactionStatus: {
            readonly codecId: "pg/text@1";
            readonly members: readonly [
              { readonly name: "PENDING"; readonly value: "PENDING" },
              { readonly name: "PAID"; readonly value: "PAID" },
            ];
          };
          readonly UserRole: {
            readonly codecId: "pg/text@1";
            readonly members: readonly [
              { readonly name: "POSTER"; readonly value: "POSTER" },
              { readonly name: "WORKER"; readonly value: "WORKER" },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: { readonly id: "uuidv4"; readonly kind: "generator" };
          readonly ref: {
            readonly column: "id";
            readonly namespace: "public";
            readonly table: "applications";
          };
        },
        {
          readonly onCreate: { readonly id: "uuidv4"; readonly kind: "generator" };
          readonly ref: {
            readonly column: "id";
            readonly namespace: "public";
            readonly table: "notifications";
          };
        },
        {
          readonly onCreate: { readonly id: "uuidv4"; readonly kind: "generator" };
          readonly ref: {
            readonly column: "id";
            readonly namespace: "public";
            readonly table: "tasks";
          };
        },
        {
          readonly onCreate: { readonly id: "uuidv4"; readonly kind: "generator" };
          readonly ref: {
            readonly column: "id";
            readonly namespace: "public";
            readonly table: "transactions";
          };
        },
        {
          readonly onCreate: { readonly id: "uuidv4"; readonly kind: "generator" };
          readonly ref: {
            readonly column: "id";
            readonly namespace: "public";
            readonly table: "users";
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract["storage"]["namespaces"];
